#!/bin/bash

cd ~
sudo apt-get install -y git vim
[ -d config ] || git clone https://github.com/cairo140/config.git

echo "
# personal configs
source \$HOME/config/bashrc" >> $HOME/.bashrc
echo "
\" personal configs
source \$HOME/config/vimrc" >> $HOME/.vimrc

mkdir -p $HOME/.vim/backup
mkdir -p $HOME/.vim/tmp

cd config
git submodule update --init

git config --global user.email "steven@stevenxu.ca"
git config --global user.name "Steven Xu"

source $HOME/.bashrc

source $HOME/config/bash/z/z.sh
$(cd bash/z && make)
