#!/bin/bash

cd ~
sudo apt-get install -y git vim
[ -d config ] || git clone https://github.com/cairo140/config.git

echo "
# personal configs
source \$HOME/config/bashrc" >> $HOME/.bashrc
echo "
\" personal configs
source \$HOME/config/vimrc" >> $HOME/.vimrc

mkdir -p $HOME/.vim/backup
mkdir -p $HOME/.vim/tmp

cd config
git submodule update --init

$(cd bash/z && make)

source $HOME/.bashrc
