#!/bin/bash

if grep -q '$HOME/config/zshrc' $HOME/.zshrc; then
  echo "~/config/zshrc already included in ~/.zshrc"
else
  echo "
  # personal configs
  source \$HOME/config/zshrc" >> $HOME/.zshrc
fi

if grep -q '$HOME/config/vimrc' $HOME/.vimrc; then
  echo "~/config/vimrc already included in ~/.vimrc"
else
  echo "
  \" personal configs
  source \$HOME/config/vimrc" >> $HOME/.vimrc
fi

mkdir -p $HOME/.vim/backup
mkdir -p $HOME/.vim/tmp

git config --global user.email "steven@stevenxu.ca"
git config --global user.name "Steven Xu"

cd config
git submodule update --init

echo "Remember to source ~/.zshrc."
